server:
    port: 8080

# the jdbc template connection
datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment4j?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    maximumPoolSize: 10

---
spring:
    profiles: dev
datasource:
    url: jdbc:mysql://localhost:3306/payment4j?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
---
spring:
    profiles: test
datasource:
    url: jdbc:mysql://test.paycompany.com:3306/payment4j?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
---
spring:
    profiles: prod
datasource:
    url: jdbc:mysql://com.paycompany:3306/payment4j?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
