package com.payment.model;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Thu Jan 05 02:42:05 CST 2017
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     * @mbg.generated Thu Jan 05 02:42:05 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     * @mbg.generated Thu Jan 05 02:42:05 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }
}